### ISSUE TITLE
MemoryObjectAllocationFailure of Cudafy.NET

### ISSUE THREAD

**Issue by mucet** [ethanbayne/OpenForensics#4]
Hello, I am taking this error in "LaunchPFACCarving" Method: How can i fix this error? What is the best solution?

**Cloo.MemoryObjectAllocationFailureComputeException: 'OpenCL error code detected: MemoryObjectAllocationFailure.'**

Details of Error:
Cloo.MemoryObjectAllocationFailureComputeException
  HResult=0x80131600
  İleti=OpenCL error code detected: MemoryObjectAllocationFailure.
  Kaynak=Cudafy.NET
  StackTrace:
   at Cloo.ComputeException.ThrowOnError(ComputeErrorCode errorCode)
   at Cloo.ComputeCommandQueue.Read[T](ComputeBufferBase`1 source, Boolean blocking, Int64 offset, Int64 region, IntPtr destination, ICollection`1 events)
   at Cloo.ComputeCommandQueue.ReadFromBufferEx[T](ComputeBufferBase`1 source, Array& destination, Boolean blocking, Int64 sourceOffset, Int64 destinationOffset, Int64 region, IList`1 events)
   at Cudafy.Host.OpenCLDevice.DoCopyFromDevice[T](Array devArray, Int64 devOffset, Array hostArray, Int64 hostOffset, Int64 count)
   at Cudafy.Host.OpenCLDevice.DoCopyFromDevice[T](Array devArray, Array hostArray)
   at OpenForensics.Engine.LaunchPFACCarving(Int32 gpuCore) in \OpenForensics-master\OpenForensics\Engine.cs:line 264
   at OpenForensics.Analysis.GPUThread(Int32 gpu, Int32 gpuCore, dataReader dataRead) in \OpenForensics-master\OpenForensics\Analysis.cs:line 1180
   at OpenForensics.Analysis.<>c__DisplayClass52_5.<FileAnalysis>b__7() in \OpenForensics-master\OpenForensics\Analysis.cs:line 891
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by ethanbayne** [comment]
Hi Mustafa,

Could I have more information regarding the environment you are running OpenForensics in so I may investigate this error further? Principly, I need to know the following:

OpenForensics Version:
Is OpenForensics is running inside a VM:
Operating System:
Processor:
Memory:
GPU:
GPU Memory:

**Comment by mucet** [comment]
Hello Ethan, thank you for your quick reply.

OpenForensics Version: v 1.65b
Is OpenForensics is running inside a VM: No its running on WorkStation
Operating System: Windows 10
Processor: Intel Xeon CPU E5-2643 v4 3.40 Ghz
Memory: 64 GB (RAM)
GPU: Nvidia Quadro K620
GPU Memory: 2 GB

**Comment by mucet** [comment]
Hi Ethan again,

This problem actually its not about OpenForensics software.
OF is throw an error because another programs are using same raw image files. So i copied its and i run the last version of OF (v1.78) with this image. And problem is solved.

**Comment by ethanbayne** [comment]
Hi Mustafa,

Thanks for following up. Using an image file that is currently in use (file locked) by another application is a situation that would cause this error. I will add some file access checks in a future version to prevent this error from occuring.

**Comment by ethanbayne** [comment]
Addressed in [commit 83a2308b926d647c5a018c1971f81be824cd1aa4](https://github.com/ethanbayne/OpenForensics/commit/83a2308b926d647c5a018c1971f81be824cd1aa4). Fix will be rolled into next release.
